image: docker:latest

stages:
  - create_image

create_image_job:
  stage: create_image
  only:
    - triggers
  tags:
    - docker
  script:
    - ls -l
    - server=reg.paradise-soft.com.tw:5000
    - appname=xunya-legion
    - docker build . -f Dockerfile.build -t $server/${appname}_build:$CI_COMMIT_REF_NAME --build-arg branch=$CI_COMMIT_REF_NAME
    - docker create --name xunya-legion-build $server/${appname}_build:$CI_COMMIT_REF_NAME
    - docker cp ${appname}-build:/$appname/$appname .
    - docker rm ${appname}-build
    - docker build . -f Dockerfile -t $server/$appname:$CI_COMMIT_REF_NAME
    - docker push $server/$appname:$CI_COMMIT_REF_NAME
    - rm $appname
    - docker image rm $server/$appname:$CI_COMMIT_REF_NAME
