image: docker:latest

stages:
  - create_image

create_image_job:
  stage: create_image
  only:
    - triggers
  tags:
    - docker
  script:
    - cp go.mod.default go.mod
    - cp go.sum.default go.sum
    - ls -l
    - server=reg.paradise-soft.com.tw:5000
    - appname=xunya-legion
    - docker build . -f Dockerfile.base -t base/$appname:$CI_COMMIT_REF_NAME --build-arg branch=$CI_COMMIT_REF_NAME
    - docker create --name base base/$appname:$CI_COMMIT_REF_NAME
    - docker cp base:/$appname/$appname .
    - docker rm base
    - docker build . -f Dockerfile -t $server/$appname:$CI_COMMIT_REF_NAME
    - docker push $server/$appname:$CI_COMMIT_REF_NAME
